---
title: Getting started with the Sense HAT
hero_image: images/banner.png
description: Explore the Sense HAT sensor board and its Python library
original_url: https://raspberrypi.org/learning/getting-started-with-the-sense-hat
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: python, sense-hat
hardware: sense-hat
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: What is a Sense HAT?
- title: Displaying text
  completion:
  - engaged
- title: Displaying a single character
- title: Displaying images
- title: Setting orientation
- title: Sensing the environment
- title: Detecting movement
- title: Using the joystick
  completion:
  - internal
- title: 'Challenge: putting it all together'
- title: 'Challenge: more ideas'
  completion:
  - external
